[build]
  base = "smartsure-frontend"
  command = "npm run build"
  publish = "smartsure-frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "http://18.118.95.249:8888/:splat"
  status = 200
  force = true